name = "PortfolioAnalysis"
uuid = "11b04c8e-0df7-46bc-9bc9-f292e2fea538"
authors = ["robfs <robfoxsimms@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BusinessDays = "4f18b42c-503e-5345-9536-bb0f25fc7038"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"

[compat]
TimeSeries = "0.23"
BusinessDays = "0.9"
julia = "1.7"

[extras]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
